### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by olimart** [yafoy/pepito#4]
```
$ devpepito
Listening on localhost:4567, CTRL+C to stop
Stopping Thin ...
Thin was started inside an existing EventMachine.run block.
Call `EventMachine.stop` to stop the reactor and quit the process.
== Sinatra has ended his set (crowd applauds)
Pepito Shell Adapter
> WARN: tilt autoloading 'tilt/erubis' in a non thread-safe way; explicit require 'tilt/erubis' suggested.
```

`ctrl+c` returns message below and server is not stopping
```
Stopping Thin ...
Thin was started inside an existing EventMachine.run block.
Call `EventMachine.stop` to stop the reactor and quit the process.
```

**Comment by olimart** [comment]
all good now.

Upon startup the last line of the log goes like this:
```
I, [2016-02-15T10:18:21.639478 #56748]  INFO -- : Starting the adapters
```

However, the pattern you've initiated follows start/started

```
I, [2016-02-15T10:18:21.637290 #56748]  INFO -- : "Info" handler starting
I, [2016-02-15T10:18:21.638153 #56748]  INFO -- : "Info" handler started successfully
``` 

Does something prevent us to log `adapters started successfully`?

**Comment by adbjesus** [comment]
On adapters, imagine for example that in the slack adapter the token is wrong. This will return an error and prevent the adapter from starting. Or maybe some configuration value is missing it will also return an error.

On handlers there are also some errors, for example if the handler is already running it won't start again.
